version: '3.3'

services:
  rsuitejs_build:
    build: ../
    container_name: 'rsuitejs_build'
    volumes:
      - dist:/usr/src/app/dist

  rsuitejs_web:
    image: nginx
    ports:
      - 80
    container_name: 'rsuitejs_web'
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist: